plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.1-SNAPSHOT" apply false
}

architectury {
    // Tell Architectury which platforms this common module supports
    common(["forge"])
}

loom {
    accessWidenerPath = file("src/main/resources/allthetrims.accesswidener")
}

dependencies {
    // Architectury API (common xplat)
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"

    // Mixin addons
    implementation(annotationProcessor("com.github.llamalad7.mixinextras:mixinextras-common:${rootProject.mixin_extras_version}"))
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${rootProject.mixin_squared_version}"))

    // Config
    modImplementation("dev.isxander.yacl:yet-another-config-lib-common:${rootProject.yacl_version}")

    // Optional compat mods (Forge)
    modCompileOnly("maven.modrinth:immersive-armors:${rootProject.immersive_armors_version}")

    // REI / EMI
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api-forge:${rootProject.rei_version}")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-forge:${rootProject.rei_version}")
    modCompileOnly("dev.emi:emi-forge:${rootProject.emi_version}:api")
    modCompileOnly("dev.emi:emi-forge:${rootProject.emi_version}")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 17
}

java {
    withSourcesJar()
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
    repositories {
        // Add repositories to publish to here.
    }
}
